export const songdata = [
  {
    id: 0,
    songName: "Vardan",
    coverPath: "/assets/vardan.jfif",
    filePath: "/songs/0.mp3",
  },
  {
    id: 1,
    songName: "Sulthan",
    coverPath: "/assets/asset 87.jpeg",
    filePath: "/songs/1.mp3",
  },
  {
    id: 2,
    songName: "Chand Baaliyan",
    coverPath: "/assets/asset 14.jpeg",
    filePath: "/songs/2.mp3",
  },
  {
    id: 3,
    songName: "Monster KGF",
    coverPath: "/assets/asset 15.jpeg",
    filePath: "/songs/3.mp3",
  },
  {
    id: 4,
    songName: "Deadwood",
    coverPath: "/assets/asset 4.jpeg",
    filePath: "/songs/4.mp3",
  },
  {
    id: 5,
    songName: "Yaaro Ne",
    coverPath: "/assets/asset 33.jpeg",
    filePath: "/songs/5.mp3",
  },
  {
    id: 6,
    songName: "Snap",
    coverPath: "/assets/snap.jfif",
    filePath: "/songs/6.mp3",
  },
  {
    id: 7,
    songName: "All Time Low",
    coverPath: "/assets/alltimelow.jfif",
    filePath: "/songs/7.mp3",
  },
  {
    id: 8,
    songName: "Naruto Theme",
    coverPath: "/assets/naruto.jfif",
    filePath: "/songs/8.mp3",
  },
  {
    id: 9,
    songName: "Enemy Arcane",
    coverPath: "/assets/enemy.jfif",
    filePath: "/songs/9.mp3",
  },
  {
    id: 10,
    songName: "Love Of Shap of You",
    coverPath: "/assets/loveshap.jpg",
    filePath: "/songs/10.mp3",
  },
  {
    id: 11,
    songName: "Hymen of the Weekened",
    coverPath: "/assets/hymen.jfif",
    filePath: "/songs/11.mp3",
  },
  {
    id: 12,
    songName: "Faded",
    coverPath: "/assets/faded.jfif",
    filePath: "/songs/12.mp3",
  },
  {
    id: 13,
    songName: "Girls like you do",
    coverPath: "/assets/girlslike.jfif",
    filePath: "/songs/13.mp3",
  },
  {
    id: 14,
    songName: "Play Date",
    coverPath: "/assets/playdate.jpg",
    filePath: "/songs/14.mp3",
  },
  {
    id: 15,
    songName: "Unstoppable",
    coverPath: "/assets/unstoppable.jpg",
    filePath: "/songs/15.mp3",
  },
  {
    id: 16,
    songName: "Kaun Hain Voh",
    coverPath: "/assets/kaun hai vo.jfif",
    filePath: "/songs/16.mp3",
  },
  {
    id: 17,
    songName: "Netflix Shape Of You",
    coverPath: "/assets/indianshapofyou.jfif",
    filePath: "/songs/17.m4a",
  },
];

